// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp.net_web_api.Models;

#nullable disable

namespace asp.net_web_api.Migrations.TemporaryDb
{
    [DbContext(typeof(TemporaryDbContext))]
    [Migration("20251129211615_temp_init")]
    partial class temp_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("asp.net_web_api.Models.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Important")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecordedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("asp.net_web_api.Models.WebVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("LatitudeCoord")
                        .HasColumnType("REAL");

                    b.Property<double?>("LongitudeCoord")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
