name: React CI/CD

on:
  push:
    branches: [main]
    paths:
     - "react-frontend/**"
  pull_request:
    branches: [main]
    paths:
     - "react-frontend/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint the code
      - name: Lint code
        run: npm run lint

      # 5. Run tests with coverage
      - name: Run tests
        run: npm test -- --watchAll=false --coverage

      # 6. Build the React app
      - name: Build app
        run: npm run build

      # 7. Upload coverage artifact (optional)
      #- name: Upload coverage report
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: coverage-report
      #    path: coverage
